export const API_PATHS = {
  AUTH: {
    SEND_OTP: '/api/auth/send-otp',
    SIGNUP: '/api/auth/signup',
    VERIFY_SIGNUP: '/api/auth/verify-signup',
    LOGIN: '/api/auth/login',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
    LOGOUT: '/api/auth/logout',
    GET_ME: '/api/auth/me',
    UPDATE_PROFILE: '/api/auth/profile',
    ADD_ADDRESS: '/api/auth/addresses',
    UPDATE_ADDRESS: (id) => `/api/auth/addresses/${id}`,
    DELETE_ADDRESS: (id) => `/api/auth/addresses/${id}`,
  },
  PETS: {
    GET_ALL: '/api/pets',
    GET_ONE: (id) => `/api/pets/${id}`,
    CREATE: '/api/pets',
    UPDATE: (id) => `/api/pets/${id}`,
    DELETE: (id) => `/api/pets/${id}`,
    UPLOAD_IMAGES: (id) => `/api/pets/${id}/images`,
    DELETE_IMAGE: (id, imageId) => `/api/pets/${id}/images/${imageId}`,
    UPLOAD_VIDEOS: (id) => `/api/pets/${id}/videos`,
    DELETE_VIDEO: (id, videoId) => `/api/pets/${id}/videos/${videoId}`,
  },
  PRODUCTS: {
    GET_ALL: '/api/products',
    GET_CATEGORIES: '/api/products/categories',
    GET_ONE: (id) => `/api/products/${id}`,
    CREATE: '/api/products',
    UPDATE: (id) => `/api/products/${id}`,
    DELETE: (id) => `/api/products/${id}`,
    UPLOAD_IMAGES: '/api/products/upload-images',
  },
  CART: {
    GET: '/api/cart',
    SYNC: '/api/cart/sync',
    ADD_ITEM: '/api/cart/items',
    UPDATE_QTY: (productId) => `/api/cart/items/${productId}`,
    REMOVE_ITEM: (productId) => `/api/cart/items/${productId}`,
    CLEAR: '/api/cart',
  },
  ORDERS: {
    CREATE: '/api/orders',
    VERIFY_PAYMENT: '/api/orders/verify-payment',
    RETRY_PAYMENT: (id) => `/api/orders/${id}/retry-payment`,
    MY_ORDERS: '/api/orders/my',
    GET_ONE: (id) => `/api/orders/${id}`,
    CANCEL: (id) => `/api/orders/${id}/cancel`,
  },
  ADMIN: {
    DASHBOARD: '/api/admin/dashboard',
    ANALYTICS: '/api/admin/analytics',
    ORDERS: '/api/admin/orders',
    UPDATE_ORDER_STATUS: (id) => `/api/admin/orders/${id}/status`,
    CUSTOMERS: '/api/admin/customers',
    SETTINGS: '/api/admin/settings',
  },
  UPLOAD: {
    IMAGE: '/api/upload/image',
    SINGLE_IMAGE: '/api/upload/single-image',
    VIDEO: '/api/upload/video',
    DELETE: '/api/upload/media',
  },
  SETTINGS: '/api/settings',
};
